{{- if .Values.signing.enabled -}}
{{- if not (or (include "gitea.gpg-signing-enabled" .) (include "gitea.ssh-signing-enabled" .)) -}}
  {{- fail "Either configure GPG signing (signing.privateKey/signing.existingSecret) or SSH signing (signing.ssh.privateKey/signing.ssh.existingSecret)" -}}
{{- end }}
{{- if and (include "gitea.gpg-signing-enabled" .) (include "gitea.ssh-signing-enabled" .) -}}
  {{- fail "Cannot configure both GPG and SSH signing simultaneously" -}}
{{- end }}
{{- if and (not (empty .Values.signing.privateKey)) (empty .Values.signing.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.gpg-key-secret-name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.signing.privateKey | b64enc }}
{{- end }}
{{- end }}
