{{- if .Values.signing.enabled -}}
{{- if and (not (empty .Values.signing.ssh.privateKey)) (empty .Values.signing.ssh.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.ssh-signing-key-secret-name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.signing.ssh.privateKey | b64enc }}
{{- end }}
{{- end }}
